### ISSUE TITLE
Control visibility and animation

### ISSUE THREAD

**Issue by lucdion** [jakemarsh/core-layout#1]
Hi, 

This is not an issue but more general questions:

1. Can we control the visibility of containers and relayout?
2. Can we animate changes? For example can we animate distribution changes?

Thanks

**Comment by jakemarsh** [comment]
Hey @luc-dion, thanks for checking out the project!

For your first question, I just realized I forgot to document one property on `Layout`:

It's called `isIncludedInLayout` and it's a `Bool`. By default it is `true`. If you set this to `false` however, it will remove it from the tree when computing. This may or may not be what you're looking for in terms of what you want "Hidden" to mean.

Which brings me to your second query. So, one important note is that **Core Layout** doesn't handle any rendering of views, and is focused on the raw computation of rectangles. 

For this reason, you can certainly animate changes between one tree of `Layout` values, and another. 
In raw **UIKit** code terms, this would mean creating a tree of `UIView`s, then `apply`ing a tree of `ComputedLayout`s to it. Then, later inside of a `UIView` animation block or `UIViewAnimator` block somewhere, you could `apply` a different tree of `ComputedLayout`s to your tree of `UIView`s.

Since you applied it inside an animation block, the change would be animated by **UIKit**.

Hope this help. Also, I'm open to feedback on how to improve the README always. Let me know what I can do to make it better in these areas.

**Comment by lucdion** [comment]
Thanks for these nice answers.
